# mkdocs.yml
site_name: Deep Glue Documentation
theme:
  name: material
  logo: images/deep_glue_logo.png  # path relative to docs/

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy