# Deep Glue CI/CD Workflow
# Install Python dependencies, run tests, lint, and publish to PyPI.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: deepglue ci_cd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs,dev]

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
        continue-on-error: true  # Allow CI to continue even if there are lint errors

      - name: Test with pytest
        run: pytest

      - name: Build package
        run: |
          pip install hatch  # Ensure hatch is installed
          hatch build  # create the distribution files 

      - name: Upload release distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists  # Ensure this matches what is expected in the publish job
          path: dist/*  # Path to the built distributions

  publish:
    name: Publish release to PyPI
    needs: build-and-deploy  # Ensure this runs after the build-and-deploy job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
