# Deploy to PyPI once CI runs successfully
name: publish to pypi

on:
  workflow_run:
    workflows: ["deepglue ci"]
    types:
      - completed  # Trigger when the CI workflow is completed

permissions:
  contents: read
  id-token: write  # Mandatory for trusted publishing

jobs:
  pypi-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if CI is successful
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/deepglue

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: List Available Artifacts Before Download
        run: |
          echo "Listing artifacts available from the CI run:"
          # List artifacts uploaded from the CI workflow
          ls -R ${{ github.workspace }}

      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists  # Match this with the artifact name from ci.yml
          path: dist/  # Path to download the artifact into

      - name: Check Download Status
        if: failure()  # This runs only if the previous step fails
        run: |
          echo "Artifact retrieval failed. Checking available files:"
          ls -R dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
